**AIM:Create a Ipython notebook to work with numpy module**
.(a)creating 1D And 2D arrays
.(b)Arithetic operations on arrays
.(c)Basic indexing,Slicing And Boolean Indexing
.(d)Transposing Arrays and Swapping axes


In [ ]:
import numpy as np

**(a) Creating 1D and 2D Arrays**

In [ ]:
#Creating 1D Array from the list
arr1d=np.array([10,20,30,40,50])#it take argument as any iterable object
print(arr1d)#the main diff b/w array & list is list seperate by ',' but array doesn't seperate by ','

[10 20 30 40 50]


In [ ]:
numbers=[10,20,30,40,50,60]
arr1d=np.array(numbers)

In [ ]:
type(arr1d)#nd means number of dimensions

numpy.ndarray

In [ ]:
#Creating 2D Array from the list
arr2d=np.array([[10,20,30],[40,50,60],[70,80,90]])
print(arr2d)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [ ]:
#properties of 1D array
arr1d.size#it returns no.of elements in array

5

In [ ]:
arr1d.ndim#ndim is no.of dimensions of given array

1

In [ ]:
arr1d.shape#it returns the onlysize because it has only one row

(5,)

In [ ]:
arr2d.size#it returns total number of elements

9

In [ ]:
arr2d.ndim#it return the no.of dimensions

2

In [ ]:
arr2d.shape#it returns the no.of rows and no.of columns

(3, 3)

In [ ]:
#creating 1D array from numpy arrange()
ar1d=np.arange(10,16)#arange(start,stop,stepsize)
print(ar1d)

[10 12 14]


In [ ]:
#creating 1d array with all zeros
zero1d=np.zeros(5)#by default the all zeros array is in float
print(zero1d)
zero1d1=np.zeros(5,dtype=int)
print(zero1d1)


[0. 0. 0. 0. 0.]
[0 0 0 0 0]


In [ ]:
#creating 2D array with all zeros
zero2d=np.zeros(())
zero2d=np.zeros((3,3))
print(zero2d)

0.0
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
#creating 1D array with all ones
one1d=np.ones(5)#by default the all zeros array is in float
print(one1d)
one1d1=np.ones(5,dtype=int)
print(one1d1)


[1. 1. 1. 1. 1.]
[1 1 1 1 1]


In [ ]:
#creating 2d array with all ones
one12d=np.ones((3,3))
print(one12d)


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
#creating Identity matrix
id_matrix=np.eye(3)
print(id_matrix)#here all diagonals are 1

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#creating arrays using numpy random module
from numpy import random

In [ ]:
#creating 1-D & 2-D arrays using randint()
rint1d = random.randint(10,size=5)#here 10 is also inclusive
print(rint1d)
rint2d=random.randint(2,35,size=(3,3))
print(rint2d)

[4 0 0 3 2]
[[19 20  3]
 [12  2 11]
 [10 30 34]]


In [ ]:
#creating 1-D ANd 2-D arrays using randn()-normal distribution
rn1d=random.randn(5)#1-D array
rn2d=random.randn(3,3)
print(rn1d)
print(rn1d.round(2))
print(rn2d)
print(rn2d.round(2))

[ 0.16459224  0.43981987  0.14754622 -1.99620197  0.19717721]
[ 0.16  0.44  0.15 -2.    0.2 ]
[[ 0.73005868 -0.2235696  -0.04625243]
 [-1.1766966   0.36107302  1.41996789]
 [ 1.15671331  0.9365896   0.07036526]]
[[ 0.73 -0.22 -0.05]
 [-1.18  0.36  1.42]
 [ 1.16  0.94  0.07]]


In [ ]:
#creating 1-D & 2-D arrays using rand()-uniform Distribution
rnd1d=random.rand(4)
print(rnd1d)
rnd2d=random.rand(3,3)
print(rnd2d)

[0.21586527 0.08305311 0.29865102 0.9814621 ]
[[0.12336933 0.13522543 0.76038584]
 [0.24127244 0.23441748 0.61325654]
 [0.11652539 0.19585299 0.7225377 ]]


In [ ]:
##creating 1-D & 2-D arrays using random()-values wil be Half interval b/w [0.0,1.0) "[ is inclusive ,) is exclusive"
rndm1d=random.random(4)
print(rndm1d)
rndm2d=random.random((2,2))
print(rndm2d)

[0.58364108 0.92759137 0.96584765 0.68945285]
[[0.73577761 0.27038439]
 [0.65509927 0.59725667]]


In [ ]:
#Create 1-D array with equal distance b/w elements - linspace()
lns1d=np.linspace(10,20,5)
print(lns1d)

[10.  12.5 15.  17.5 20. ]


**(B)Arithemetic operations on arrays**

In [ ]:
import numpy as np

In [ ]:
a1=np.array([2,4,3,1])
a2=np.arange(5,9)
n=5
m=2

In [ ]:
a1+n


array([7, 9, 8, 6])

In [ ]:
print(a2-3)

[2 3 4 5]


In [ ]:
a1/m

array([1. , 2. , 1.5, 0.5])

In [ ]:
print(a1)
print(m)
print(a1/m)#floating point divison

[2 4 3 1]
2
[1.  2.  1.5 0.5]


In [ ]:
print(a1)
print(m)
print(a1//m)#integer divison

[2 4 3 1]
2
[1 2 1 0]


In [ ]:
print(a2)
print(a2**2)

[5 6 7 8]
[25 36 49 64]


**arithematic operation between arrays**

In [ ]:
  print("a1=",a1)
  print("a2=",a2)

a1= [2 4 3 1]
a2= [5 6 7 8]


In [ ]:
a1+a2

array([ 7, 10, 10,  9])

In [ ]:
 a3=[4,5,6,7,8,9,10]

In [ ]:
a1+a3#to perform addition b/w two two arrays there should be equal size of both arrays

ValueError: ignored

In [ ]:
a1/a2

array([0.4       , 0.66666667, 0.42857143, 0.125     ])

In [ ]:
a1//a2

array([0, 0, 0, 0])

In [ ]:
a1/np.zeros(4)#here we will not get runtime error we will get only runtime warning

<ipython-input-19-6f0b6ee0b805>:1: RuntimeWarning: divide by zero encountered in true_divide
  a1/np.zeros(4)


array([inf, inf, inf, inf])

In [ ]:
from numpy import random

In [ ]:
#2-D arrays
b1=random.randint(5,20,size=(3,3))
b2=random.randint(1,10,size=(3,3))
b3=np.eye(3)

In [ ]:
print(b1)
print(b2)
print(b3)

[[12 14 10]
 [13 15 10]
 [12 19  5]]
[[7 4 7]
 [8 1 9]
 [6 9 8]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
b1+b3

array([[13., 14., 10.],
       [13., 16., 10.],
       [12., 19.,  6.]])

In [ ]:
b1/b3

<ipython-input-26-aa70cb8176f3>:1: RuntimeWarning: divide by zero encountered in true_divide
  b1/b3


array([[12., inf, inf],
       [inf, 15., inf],
       [inf, inf,  5.]])

In [ ]:
b1//b3

<ipython-input-27-5c43eae19345>:1: RuntimeWarning: divide by zero encountered in floor_divide
  b1//b3


array([[12., inf, inf],
       [inf, 15., inf],
       [inf, inf,  5.]])

In [ ]:
print(5//2)#here int/int only returns the int as result in integer divison
print(5//2.0)
print(5.0//2.0)

2
2.0
2.0


**Boolean indexing**

In [ ]:
import numpy as np


In [ ]:
arr1d=np.random.randint(-10,10,size=8)
print(arr1d)

[-8  0  1 -6 -5  9  2 -4]


In [ ]:
bool_1d=arr1d>=0
print(bool_1d)
print(arr1d[bool_1d])

[False  True  True False False  True  True False]
[0 1 9 2]


In [ ]:
arr2d=np.arange(5,21).reshape(4,4)
print(arr2d)

[[ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [ ]:
bool_2d=arr2d < 13
print(bool_2d)

[[ True  True  True  True]
 [ True  True  True  True]
 [False False False False]
 [False False False False]]


In [ ]:
print(arr2d[bool_2d])

[ 5  6  7  8  9 10 11 12]


**Fancy Indexing**

In [ ]:
ar2d=np.arange(10,26).reshape(4,4)

In [ ]:
ar2d

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21],
       [22, 23, 24, 25]])

In [ ]:
ar2d[2,3]

21

In [ ]:
ar2d[[2,3]]

array([[18, 19, 20, 21],
       [22, 23, 24, 25]])

In [ ]:
ar2d[[3,1]]

array([[22, 23, 24, 25],
       [14, 15, 16, 17]])

In [ ]:
ar2d[[3,3]][:,[2,0]]#combination of slicing and fancy indexing

array([[24, 22],
       [24, 22]])

In [ ]:
ar2d[[3,1],[2,3]]

array([24, 17])

**Transpose**

In [ ]:
ar2d.T

array([[10, 14, 18, 22],
       [11, 15, 19, 23],
       [12, 16, 20, 24],
       [13, 17, 21, 25]])

In [ ]:
ar2d.transpose()

array([[10, 14, 18, 22],
       [11, 15, 19, 23],
       [12, 16, 20, 24],
       [13, 17, 21, 25]])