In [ ]:
import numpy as np
from numpy import random

In [ ]:
ar1=random.randint(low=1,high=20,size=(4,4))

In [ ]:
ar2=random.randint(low=1,high=20,size=(4,4))

In [ ]:
ar1

array([[13,  6,  9,  5],
       [ 5, 16, 18, 10],
       [14, 13, 17, 15],
       [ 6, 14,  5,  7]])

In [ ]:
ar2

array([[17, 18,  8, 10],
       [15, 11, 18, 18],
       [ 8,  9,  6, 13],
       [16,  1,  8,  8]])

**sum**

In [ ]:
np.sum(ar1)

173

In [ ]:
np.sum(ar1,axis=0)#axis 1 means coloumn wise 13+5+14+6

array([38, 49, 49, 37])

In [ ]:
np.sum(ar1,axis=1)# axis 1 means row wise 13+6+9+5

array([33, 49, 59, 32])

In [ ]:
np.sum(ar1,where = ar1>11)#it will sum numbers greater than 11

120

In [ ]:
np.sum(ar1,axis=0,where=ar1>11)

array([27, 43, 35, 15])

In [ ]:
np.sum(ar1,axis=1,where=ar1<11)

array([20, 15,  0, 18])

**Min & Max**

In [ ]:
np.min(ar2)#gives minimum value of array

1

In [ ]:
np.max(ar2)#gives maximum value of array

18

**argmin() & argmax()**

In [ ]:
np.argmin(ar2)#gives index of minimum value of array 0 1 2 3
                                                    4 5 6 7

13

In [ ]:
np.argmax(ar2)

1

**cumsum**

In [ ]:
ar1

array([[13,  6,  9,  5],
       [ 5, 16, 18, 10],
       [14, 13, 17, 15],
       [ 6, 14,  5,  7]])

In [ ]:
np.cumsum(ar1)#if no argument pass it will add on by one

array([ 13,  19,  28,  33,  38,  54,  72,  82,  96, 109, 126, 141, 147,
       161, 166, 173])

In [ ]:
np.cumsum(ar1,axis=0)#column wise

array([[13,  6,  9,  5],
       [18, 22, 27, 15],
       [32, 35, 44, 30],
       [38, 49, 49, 37]])

In [ ]:
np.cumsum(ar1,axis=1)

array([[13, 19, 28, 33],
       [ 5, 21, 39, 49],
       [14, 27, 44, 59],
       [ 6, 20, 25, 32]])

**Cum prod()**

In [ ]:
ar2

array([[17, 18,  8, 10],
       [15, 11, 18, 18],
       [ 8,  9,  6, 13],
       [16,  1,  8,  8]])

In [ ]:
np.cumprod(ar2)#ex 17*18=306,306*8=2448 -----

array([              17,              306,             2448,
                  24480,           367200,          4039200,
               72705600,       1308700800,      10469606400,
            94226457600,     565358745600,    7349663692800,
        117594619084800,  117594619084800,  940756952678400,
       7526055621427200])

In [ ]:
np.cumprod(ar1)

array([              13,               78,              702,
                   3510,            17550,           280800,
                5054400,         50544000,        707616000,
             9199008000,     156383136000,    2345747040000,
         14074482240000,  197042751360000,  985213756800000,
       6896496297600000])

In [ ]:
np.cumprod(ar2,axis=0)#column wise

array([[   17,    18,     8,    10],
       [  255,   198,   144,   180],
       [ 2040,  1782,   864,  2340],
       [32640,  1782,  6912, 18720]])

In [ ]:
np.cumprod(ar2,axis=1)

array([[   17,   306,  2448, 24480],
       [   15,   165,  2970, 53460],
       [    8,    72,   432,  5616],
       [   16,    16,   128,  1024]])

In [ ]:
np.cumprod(ar1,axis=0)

array([[   13,     6,     9,     5],
       [   65,    96,   162,    50],
       [  910,  1248,  2754,   750],
       [ 5460, 17472, 13770,  5250]])

In [ ]:
np.cumprod(ar1,axis=1)

array([[   13,    78,   702,  3510],
       [    5,    80,  1440, 14400],
       [   14,   182,  3094, 46410],
       [    6,    84,   420,  2940]])

**Mean()**

In [ ]:
normd=random.randn(3,3)

In [ ]:
normd

array([[-0.02985428,  1.36138865,  0.26841622],
       [-1.99537734, -0.04359445,  0.40138637],
       [-1.82569189, -1.2872212 , -0.17378574]])

In [ ]:
np.mean(normd)

-0.36937040503101704

In [ ]:
np.mean(normd,axis=0)

array([-1.28364117,  0.010191  ,  0.16533895])

In [ ]:
np.mean(normd,axis=1)

array([ 0.53331686, -0.5458618 , -1.09556627])

**std()**

In [ ]:
np.std(normd)

1.046859861015639

In [ ]:
np.std(normd,axis=0)

array([0.88926354, 1.08195908, 0.24586505])

In [ ]:

np.std(normd,axis=1)

array([0.5980627 , 1.04093658, 0.68786975])

**Var()**

In [ ]:
np.var(normd)

1.0959155686056832

In [ ]:
np.var(normd,axis=0)

array([0.79078964, 1.17063546, 0.06044962])

In [ ]:
np.var(normd,axis=1)

array([0.35767899, 1.08354896, 0.4731648 ])

***v ***