**universal functions of numpy**

In [ ]:
#unary functions
#is abs() - returns absolute  value
import numpy as np
print(np.abs(-2.56))
print(np.abs(np.array([2,-3,4,-5])))
print(np.abs(np.array([-2,3.5,6,-4.56])))


2.56
[2 3 4 5]
[2.   3.5  6.   4.56]


In [ ]:
#fabs()-floating point absolute value
np.fabs(-4)
print(np.fabs(np.array([-3,2,-5,9])))
#print(np.fbs([-3.96,-11.5,12.7,-99.99]))


[3. 2. 5. 9.]


In [ ]:
x=np.array([1,2,3,5])
y=np.array([4,0,6,8])
np.divide(x,y)

<ipython-input-10-b064ef355305>:3: RuntimeWarning: divide by zero encountered in true_divide
  np.divide(x,y)


array([0.25 ,   inf, 0.5  , 0.625])